name: metricboost
services:
  mysql:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: metric_boost
    ports:
      - "5523:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always

